#!/bin/bash
# --------------------------------------------------------------------------
# This script installs files and services for the server part of this project.
#
# Author: Bernhard Bablok
# License: GPL3
#
# Website: https://github.com/bablokb/pico-e-ink-daily
#
# --------------------------------------------------------------------------

PACKAGES="python3-pip python3-tz libxslt1.1"
PACKAGES_PIP="caldav"
PROJECT="pico-e-ink-daily"

# --- basic packages   ------------------------------------------------------

check_packages() {
  local p
  for p in "$@"; do
    echo -en "Checking $p ... " >&2
    dpkg -s "$p" 2>/dev/null | grep -q "Status.*ok" || return 0
    echo "ok" >&2
  done
  return 1
}

get_new_packages() {
  local p packages
  for p in "$@"; do
    echo -en "Checking $p ... " >&2
    if dpkg -s "$p" 2>/dev/null | grep -q "Status.*ok"; then
      echo "ok" >&2
    else
      echo "not installed" >&2
      packages+=" $p"
    fi
  done
  echo "$packages"
}

install_packages() {
  new_packages=$(get_new_packages $PACKAGES)
  if [ -n "$new_packages" ]; then
    echo -e "[INFO] installing additional packages" 2>&1
    apt-get update
    apt-get -y --no-upgrade install $new_packages
  fi

  # install PIP3 packages
  [ -n "$PACKAGES_PIP" ] && pip3 --disable-pip-version-check install $PACKAGES_PIP
}

# --- install specific files   ----------------------------------------------

install_files() {
  echo -e "[INFO] installing project files" 2>&1

  for f in `find $(dirname "$0")/../server/ -type f -not -name "*.pyc"`; do
    target="${f#*server}"
    target_dir="${target%/*}"
    [ ! -d "$target_dir" ] && mkdir -p "$target_dir"
    cp "$f" "$target"
    chown root:root "$target"
  done
  chmod 755 /usr/local/sbin/calendar2json.py

  # create configuration file
  if [ ! -f "/etc/${PROJECT}.json" ]; then
    cp -a "/etc/${PROJECT}.defaults.json" "/etc/${PROJECT}.json"
    echo -e "[INFO] created configuration file: /etc/${PROJECT}.json" 2>&1
  fi
}

# --- activate service   ----------------------------------------------------

enable_services() {
  echo -e "[INFO] enabeling py-calendar2json.service" 2>&1
  systemctl enable "py-calendar2json.service"
}

# --- main program   --------------------------------------------------------

install_packages

install_files
enable_services

echo -e "[INFO] installation completed" 2>&1
